import React from 'react'

function Sozlesmeler({ res }) {
    return (
        <>
            <h3 style={{ margin: "1rem 0 .25rem 0" }}>Ön Bilgilendirme Koşulları</h3>
            <div style={{ display: "flex", width: "100%", height: "80px", overflowY: "scroll" }}>
                <p>
                    PLATFORM SAĞLAMA SÖZLEŞMESİ<br />
                    1. TARAFLAR: <br />
                    1. Müşteri Ad		   : {res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.firstName} {res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.lastName}<br />
                    Adresi			   :{
                        res && res?.acceptedClientAdvertisementBid && res?.acceptedClientAdvertisementBid?.clientAdvertisement &&
                            res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.company === null ? `` : res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.company?.address.neighborhood / res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.company?.address?.district / res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.company?.address?.province
                    }<br />
                    Telefonu		   : {res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.phone} <br />
                    Eposta			   : {res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.email}<br />
                    Vergi No / Tc Kimlik No : {res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.company === null ? `` : res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.company?.taxNumber}<br />
                    <br />
                    2. Taşıyıcı Ünvanı	   : {res?.acceptedClientAdvertisementBid?.driverBidder?.company?.commercialTitle} <br />
                    Adresi			   : {res?.acceptedClientAdvertisementBid?.driverBidder?.company?.address?.neighborhood} {res?.acceptedClientAdvertisementBid?.driverBidder?.company?.address?.district} {res?.acceptedClientAdvertisementBid?.driverBidder?.company?.address?.province} <br />
                    Telefonu		   : {res?.acceptedClientAdvertisementBid?.driverBidder?.phone}<br />
                    Vergi No       : {res?.acceptedClientAdvertisementBid?.driverBidder?.company?.taxNumber}<br />
                    <br />
                    3. Platform Sağlayıcı<br />
                    Ünvanı			:Özkanlar Bilişim İç Ve Dış Ticaret Limited ŞTİ (LOJİSTER)<br />
                    Pamukkale Vergi Dairesi Vergi No:6980823245<br />
                    Adresi		:İncilipınar Mah. Fevzi Çakmak Bulvarı No:280 Pamukkale/DENİZLİ<br />
                    <br />
                    İşbu Sözleşme kapsamında bundan böyle, yukarıda bilgilerine yer verilen Müşteri ve Taşıyıcı birlikte “Kullanıcılar” ve ayrı ayrı “Kullanıcı” olarak;  Müşteri, Taşıyıcı ve Lojister birlikte “Taraflar”, ayrı ayrı “Taraf” olarak anılacaktır. <br />
                    <br />
                    2. TANIMLAR <br />
                    İşbu Sözleşme kapsamında aşağıda belirtilen ifadeler, yanlarında yer alan anlamları taşıyacaktır: <br />
                    LOJİSTER: Özkanlar Bilişim İç Ve Dış Ticaret Limited ŞTİ. <br />
                    Müşteri /Yük Sahibi : Web Sitesi’ne veya mobil uygulamaya üye olan ve Web Sitesi ile mobil uygulama üzerinde sunulan hizmetlerden faydalanan, emtiası taşınan işbu sözleşme ile belirtilen hüküm ve koşullar çerçevesinde faydalanan kişileri ifade eder. <br />
                    Müşteri / Yük Sahibi Yetkilisi: Müşteri ile taşıyıcı tarafından Web Sitesi ve mobil uygulama üzerinden Hizmet alımlarını bilfiil gerçekleştirmek üzere yetkilendirilen ve isim ve irtibat bilgileri LOJİSTER ’a bildirilen kişi veya kişiler, <br />
                    Taşıyıcı: Web Sitesi’ne veya mobil uygulamaya üye olan ve Web Sitesi ile mobil uygulama üzerinde sunulan hizmetlerden faydalanan, emtia taşıma hizmetini sağlayan, işbu sözleşme ile belirtilen hüküm ve koşullar çerçevesinde faydalanan kişileri ifade eder. <br />
                    Alıcı: Müşteri tarafından bildirilen ve Müşteri’ nin sevk irsaliyesinde belirtilmiş olan, taşınan emtianın teslim edileceği kişi veya alıcının yetkilisi, <br />
                    Taraflar: LOJİSTER, Müşteri ve Taşıyıcı. <br />
                    Sözleşme: LOJİSTER ile Müşteri ve Taşıyıcı arasında elektronik ortamda akdedilen işbu sözleşme, Platform: Hizmet sunulan www.lojister.com ( website) ve LOJİSTER (IOS/Android tabanlı mobil uygulama). <br />
                    Elektronik Teklif: LOJİSTER’ya ait web sitesi, mobil uygulama ve yazılım üzerinden elektronik ortamda Müşteri’den taşınacak emtia hakkında bilgilerin alınarak navluna ilişkin oluşturulan teklif, <br />
                    Web Sitesi: Elektronik Teklif’in iletilmesi, iş emirlerinin iletilmesi, emtianın takibi ve taşımanın durumu hakkında bilgi verilmesi başta olmak üzere raporlamalar ile işbu sözleşme ile tariflenen koşul ve şartlarda taşıma işinin yapılması için navlun bedelinin ödenmesi işlerinin bütünün gerçekleştirilmesine imkân sağlayan, LOJİSTER’ a ait www.lojister.com adresindeki web sitesi, <br />
                    Mobil uygulama: Elektronik Teklif’in iletilmesi, iş emirlerinin iletilmesi, emtianın takibi ve taşımanın durumu hakkında bilgi verilmesi başta olmak üzere raporlamalar ile işbu sözleşme ile tariflenen koşul ve şartlarda taşıma işinin yapılması için navlun bedelinin ödenmesi işlerinin bütünün gerçekleştirilmesine imkan sağlayan, LOJİSTER’ a ait lojister adındaki mobil uygulama, <br />
                    Hizmet: LOJİSTER platformunun kullanılması suretiyle taraflar arasında işbu Sözleşme kapsamında sağlanacak emtia taşıma hizmeti. <br />
                    <br />
                    3.SÖZLEŞME KONUSU HİZMET VE ÜRÜN BEDELİ <br />
                    3.1. Nakliye bedeli ve anlaşılan şartlar ödeme onay sayfasında, nakliye özellikleri ise “ilanlarım” bölümünde yer almaktadır. <br />
                    3.2. Emtiaya verilen teklifler fiyatlar satış fiyatıdır. Kullanıcı bu teklifler arasından kendisine en uygun olanı seçerek ödemeyi gerçekleştirir. <br />
                    3.3. Sözleşme konusu mal ya da hizmetin tüm vergiler dâhil satış fiyatı aşağıdaki tabloda gösterilmiştir. <br />
                    <table>
                        <tr>
                            <th>HİZMET/ÜRÜN	</th>
                            <th>Ücret</th>
                        </tr>
                        <tr>
                            <td>Nakliye Bedeli</td>
                            <td>{res?.price} TL</td>
                        </tr>
                        <tr>
                            <td>Sigorta Bedeli</td>
                            <td> </td>
                        </tr>
                        <tr>
                            <td>Toplam :</td>
                            <td>{res?.price} TL</td>
                        </tr>
                    </table>
                    <br />
                    4. İPTAL VE İADE KOŞULLARI <br />
                    4.1.Herhangi bir sebeple "Üye"likten çıkarılmış veya "Üye"liği durdurulmuş veya üyeliği askıya alınmış kullanıcının PLATFORMA girmek için yeni üyelik hesabı açması ve bu yeni üyeliğinin LOJİSTER tarafından tespit edilmesi halinde; bu kullanıcının tüm "LOJİSTR Üyelik Hesapları"nı, herhangi bir ihtara gerek olmaksızın iptal etme ve işbu sözleşmeyi herhangi bir ücret iade, tazminat veya cezai şart yükümlülüğü olmadan tek taraflı olarak feshetme hakkını LOJİSTER saklı tutmaktadır. <br />
                    4.2."Yük sahibi/Müşteri ve Taşıyıcı", platform üzerinden "LOJİSTER" web site ve mobil uygulamaya ait alt yapıyı kullanarak yapmış olduğu hizmet alma ve hizmet sağlama talepleri ile "LOJİSTER" tarafından belirlenmiş üyelik şartlarını ve usullerini de kabul etmiş sayılır. İstisnai durumlar hariç, "Yük sahibi/Müşteri ve Taşıyıcı" tarafından yapılan hizmet alma ve hizmet sağlama talepleri geri çekilemez veya iptal edilemez. <br />
                    4.3.Sadece ürünün “Yük veren/Müşteri” tarafından Taşıyıcıya verilmemesi veya Taşıyıcıya verilmeden sağlanması talep edilen hizmetin Yük sahibi/ Müşteri tarafından iptal edilmesi halinde; LOJİSTER hesabında bloke edilen ödeme 750 TL İptal Bedeli cezai şart düşülerek Yük Sahibine iade edilir. <br />
                    4.4.İADE:Taşıyıcının emtiayı teslim aldığını, teslim alma saatinden itibaren 24 saat içinde sistem üzerinden onaylaması üzerine hizmet bedeli Taşıyıcıya ödenir. Ancak Alıcı tarafından teslim edilen emtiada uygunsuzluk veya herhangi bir sorun yaşaması halinde; ürünü teslim alma anından başlayacak 24 saatlik süre içinde “Alıcı” ya da “Müşteri”, “LOJİSTER” Müşteri Hizmetlerini arayarak sunulan hizmete ilişkin yaşadığı sorunu bildirmelidir. Müşteri Hizmetlerine sorununu bildirmesinden itibaren 7 iş günü süre içinde “Yük sahibi/Müşteri” “Taşıyıcıya”ya karşı yasal yollara müracaat ettiğini belgeleyen evrak sunması halinde; ürün bedeli Taşıyıcı’ya iade edilmeyecek, uyuşmazlık sonuçlanana dek LOJİSTER’ ın anlaşmalı ödeme kuruluşunun hesabında bloke edilecek, başvurulan merciinin kararı çıktığında bu karara göre hareket edilecektir. “Yük sahibi/Müşteri”, uyuşmazlık konusu karara bağlanana dek ürün bedelinin bloke edilmesi nedeniyle “LOJİSTER”a karşı şikâyet/dava yoluna başvurmayacağını, “LOJİSTER”dan herhangi bir talepte bulunmayacağını kabul, beyan ve taahhüt eder. <br />
                    <br />
                    5. SÖZLEŞMENİN KONUSU: <br />
                    5.1. Lojister işbu Sözleşme kapsamında, Müşteri olarak yükünü taşıtmak isteyen firmalar ile taşıma hizmetini sağlayacak olan lojistik firmalarına www.lojister.com (“Site”) ve Lojister (“mobil uygulama”) üzerinden teknolojik alt yapısı olan bir platform (“Platform”) sağlama hizmeti sunmaktadır. Bu kapsamda Taşıyıcı ve Müşteri Platform’dan temelde aşağıdaki faydaları sağlayabilmektedir: <br />
                    • Müşteri taşıma talebi ile ilgili ürün, araç, tarih ve saat gibi bilgileri girerek ilan oluşturabilmektedir. <br />
                    • Taşıyıcı, sağlayacağı lojistik hizmetine karşılık olarak uygun bulduğu hizmet bedelini Platform’a girerek fiyat teklifi sunar. Müşteri de verilen teklifleri Platform üzerinden inceleyerek teklifler arasından kendine en uygun teklifi kabul ederek ödemeyi yapabilmektedir <br />
                    • Müşteri de Platform üzerinden verilen teklifleri inceleyerek kendine en uygun teklifi kabul ederek ödemeyi yapabilmetedir. <br />
                    5.2.Müşteri ve Taşıyıcı, Platform’daki kullanıcı şifresinin belirlenmesi ve korunması hususlarından kendileri bizzat sorumlu olmaktadır. Bu anlamda Kullanıcılar, kullanıcı adı ve şifresini üçüncü kişilerle herhangi bir şekilde paylaşmaması gerektiğinin bilincindedir. Bu hususta, Kullanıcılar, kullanıcı şifre ve adının kendi ihmal yahut kusurları nedeniyle başka kişiler tarafından kötü niyetle kullanılmasından dolayı doğrudan sorumlu olacaktır. LOJİSTER, bu sebeple ödemek zorunda kalacağı her türlü adli/idari para cezası ve/veya tazminat bedelini ilgili Kullanıcı’ya aynen rücu etme hakkına sahiptir. <br />
                    5.3.Müşteri, taşınmasını istediği Yükü taşıtmak için Platform üzerinde bir hizmet talebi oluşturduktan sonra Lojister, Platform’da kayıtlı Taşıyıcı’ lar tarafından kendisine iletilen taşıma ücret tekliflerini (“Teklif”) Müşteri bilgisi vermeksizin Platform’da listeleyerek Müşteri’nin kendisine en uygun gelen seçeneği seçmesine imkân sağlamaktadır. Özellikle belirtmek gerekir ki, Lojister yalnızca Müşteri ve Taşıyıcı’yı bir araya getiren Platform sağlama görevini üstlenmiş olup taşıma işlemlerini kendisi üstlenmemekte ve bu hususta sorumluluk kabul etmemektedir. <br />
                    5.4.Müşteri, Platform üzerinden Teklif’i kabul etmesi akabinde Yük’ünü, seçmiş olduğu Teklif’te belirtilen şartlara uygun olarak Taşıyıcı’ya teslim edecektir. Taşıyıcı da belirtilen şartlara uygun olarak Alıcı’ya yükü teslim edecektir. <br />
                    5.5.Lojister Platformu (Web Sitesi/IOS, Android tabanlı mobil uygulama) , www.lojister.com adresinde yer alan sitemizdeki web sayfaları ve ona bağlı tüm sayfalar ile akıllı telefonlardaki IOS/Android tabanlı mobil uygulamaları, Özkanlar Bilişim İç Ve Dış Ticaret Limited ŞTİ (“LOJİSTER”)’ın markasıdır ve onun tarafından işletilir. <br />
                    <br />
                    6. DELİL SÖZLEŞMESİ VE İHTİLAFLARIN ÇÖZÜMÜ <br />
                    6.1.Sözleşme’den doğabilecek her türlü ihtilafta Platform üzerinden gönderilen e-mail, telefon görüşme kayıtları ve cep telefonuna gönderilen SMS bilgilendirme ve kayıtları delil niteliğinde olup, ayrıca Tarafların ticari defter ve kayıtları kesin delil olarak kabul edilecektir. <br />
                    6.2. İşbu Sözleşme Türk hukukuna tabi olup, Sözleşme’nin uygulanmasından ve yorumundan doğan ihtilaflarda Denizli Mahkemeleri ve İcra Daireleri yetkilidir. <br />

                </p>
            </div>
            <h3 style={{ margin: "1rem 0 .25rem 0" }}>Mesafeli Satış Sözleşmesi</h3>
            <div style={{ display: "flex", width: "100%", height: "80px", overflowY: "scroll" }}>
                <p>
                    PLATFORM SAĞLAMA SÖZLEŞMESİ<br />
                    1. TARAFLAR:<br />
                    1. Müşteri Ad		   : {res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.firstName} {res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.lastName}<br />
                    Adresi			   :{
                        res && res?.acceptedClientAdvertisementBid && res?.acceptedClientAdvertisementBid?.clientAdvertisement &&
                            res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.company === null ? `` : res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.company?.address.neighborhood / res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.company?.address?.district / res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.company?.address?.province
                    }<br />
                    Telefonu		   : {res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.phone} <br />
                    Eposta			   : {res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.email}<br />
                    Vergi No / Tc Kimlik No : {res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.company === null ? `` : res?.acceptedClientAdvertisementBid?.clientAdvertisement?.client?.company?.taxNumber}<br />
                    <br />
                    2. Taşıyıcı Ünvanı	   : {res?.acceptedClientAdvertisementBid?.driverBidder?.company?.commercialTitle} <br />
                    Adresi			   : {res?.acceptedClientAdvertisementBid?.driverBidder?.company?.address?.neighborhood} {res?.acceptedClientAdvertisementBid?.driverBidder?.company?.address?.district} {res?.acceptedClientAdvertisementBid?.driverBidder?.company?.address?.province} <br />
                    Telefonu		   : {res?.acceptedClientAdvertisementBid?.driverBidder?.phone}<br />
                    Vergi No       : {res?.acceptedClientAdvertisementBid?.driverBidder?.company?.taxNumber}<br />
                    <br />
                    3. Platform Sağlayıcı<br />
                    Ünvanı			:Özkanlar Bilişim İç Ve Dış Ticaret Limited ŞTİ (LOJİSTER)<br />
                    Pamukkale Vergi Dairesi Vergi No:6980823245<br />
                    Adresi		:İncilipınar Mah. Fevzi Çakmak Bulvarı No:280 Pamukkale/DENİZLİ<br />
                    <br />
                    İşbu Sözleşme kapsamında bundan böyle, yukarıda bilgilerine yer verilen Müşteri ve Taşıyıcı birlikte “Kullanıcılar” ve ayrı ayrı “Kullanıcı” olarak;  Müşteri, Taşıyıcı ve Lojister birlikte “Taraflar”, ayrı ayrı “Taraf” olarak anılacaktır.<br />
                    <br />
                    2. TANIMLAR<br />
                    İşbu Sözleşme kapsamında aşağıda belirtilen ifadeler, yanlarında yer alan anlamları taşıyacaktır:<br />
                    LOJİSTER: Özkanlar Bilişim İç Ve Dış Ticaret Limited ŞTİ.<br />
                    Müşteri /Yük Sahibi : Web Sitesi’ne veya mobil uygulamaya üye olan ve Web Sitesi ile mobil uygulama üzerinde sunulan hizmetlerden faydalanan, emtiası taşınan işbu sözleşme ile belirtilen hüküm ve koşullar çerçevesinde faydalanan kişileri ifade eder.<br />
                    Müşteri / Yük Sahibi Yetkilisi: Müşteri ile taşıyıcı tarafından Web Sitesi ve mobil uygulama üzerinden Hizmet alımlarını bilfiil gerçekleştirmek üzere yetkilendirilen ve isim ve irtibat bilgileri LOJİSTER ’a bildirilen kişi veya kişiler,<br />
                    Taşıyıcı: Web Sitesi’ne veya mobil uygulamaya üye olan ve Web Sitesi ile mobil uygulama üzerinde sunulan hizmetlerden faydalanan, emtia taşıma hizmetini sağlayan, işbu sözleşme ile belirtilen hüküm ve koşullar çerçevesinde faydalanan kişileri ifade eder.<br />
                    Alıcı: Müşteri tarafından bildirilen ve Müşteri’ nin sevk irsaliyesinde belirtilmiş olan, taşınan emtianın teslim edileceği kişi veya alıcının yetkilisi,<br />
                    Taraflar: LOJİSTER, Müşteri ve Taşıyıcı.<br />
                    Sözleşme: LOJİSTER ile Müşteri ve Taşıyıcı arasında elektronik ortamda akdedilen işbu sözleşme, Platform: Hizmet sunulan www.lojister.com ( website) ve LOJİSTER (IOS/Android tabanlı mobil uygulama).<br />
                    Elektronik Teklif: LOJİSTER’ya ait web sitesi, mobil uygulama ve yazılım üzerinden elektronik ortamda Müşteri’den taşınacak emtia hakkında bilgilerin alınarak navluna ilişkin oluşturulan teklif,<br />
                    Web Sitesi: Elektronik Teklif’in iletilmesi, iş emirlerinin iletilmesi, emtianın takibi ve taşımanın durumu hakkında bilgi verilmesi başta olmak üzere raporlamalar ile işbu sözleşme ile tariflenen koşul ve şartlarda taşıma işinin yapılması için navlun bedelinin ödenmesi işlerinin bütünün gerçekleştirilmesine imkân sağlayan, LOJİSTER’ a ait www.lojister.com adresindeki web sitesi,<br />
                    Mobil uygulama: Elektronik Teklif’in iletilmesi, iş emirlerinin iletilmesi, emtianın takibi ve taşımanın durumu hakkında bilgi verilmesi başta olmak üzere raporlamalar ile işbu sözleşme ile tariflenen koşul ve şartlarda taşıma işinin yapılması için navlun bedelinin ödenmesi işlerinin bütünün gerçekleştirilmesine imkan sağlayan, LOJİSTER’ a ait lojister adındaki mobil uygulama,<br />
                    Hizmet: LOJİSTER platformunun kullanılması suretiyle taraflar arasında işbu Sözleşme kapsamında sağlanacak emtia taşıma hizmeti.<br />
                    <br />
                    3.SÖZLEŞME KONUSU HİZMET VE ÜRÜN BEDELİ<br />
                    3.1. Nakliye bedeli ve anlaşılan şartlar ödeme onay sayfasında, nakliye özellikleri ise “ilanlarım” bölümünde yer almaktadır.<br />
                    3.2. Emtiaya verilen teklifler fiyatlar satış fiyatıdır. Kullanıcı bu teklifler arasından kendisine en uygun olanı seçerek ödemeyi gerçekleştirir.<br />
                    3.3. Sözleşme konusu mal ya da hizmetin tüm vergiler dâhil satış fiyatı aşağıdaki tabloda gösterilmiştir.<br />
                    <table>
                        <tr>
                            <th>HİZMET/ÜRÜN</th>
                            <th>Ücret</th>
                        </tr>
                        <tr>
                            <td>Nakliye Bedeli</td>
                            <td>{res?.price} TL</td>
                        </tr>
                        <tr>
                            <td>Sigorta Bedeli</td>
                            <td> </td>
                        </tr>
                        <tr>
                            <td>Toplam :</td>
                            <td>{res?.price} TL </td>
                        </tr>
                    </table>

                    4. SÖZLEŞMENİN KONUSU:<br />
                    4.1. Lojister işbu Sözleşme kapsamında, Müşteri olarak yükünü taşıtmak isteyen firmalar ile taşıma hizmetini sağlayacak olan lojistik firmalarına www.lojister.com (“Site”) ve Lojister (“mobil uygulama”) üzerinden teknolojik alt yapısı olan bir platform (“Platform”) sağlama hizmeti sunmaktadır. Bu kapsamda Taşıyıcı ve Müşteri Platform’dan temelde aşağıdaki faydaları sağlayabilmektedir:<br />
                    • Müşteri taşıma talebi ile ilgili ürün, araç, tarih ve saat gibi bilgileri girerek ilan oluşturabilmektedir.<br />
                    • Taşıyıcı, sağlayacağı lojistik hizmetine karşılık olarak uygun bulduğu hizmet bedelini Platform’a girerek fiyat teklifi sunar. Müşteri de verilen teklifleri Platform üzerinden inceleyerek teklifler arasından kendine en uygun teklifi kabul ederek ödemeyi yapabilmektedir<br />
                    • Müşteri de Platform üzerinden verilen teklifleri inceleyerek kendine en uygun teklifi kabul ederek ödemeyi yapabilmetedir.<br />
                    4.2.Müşteri ve Taşıyıcı, Platform’daki kullanıcı şifresinin belirlenmesi ve korunması hususlarından kendileri bizzat sorumlu olmaktadır. Bu anlamda Kullanıcılar, kullanıcı adı ve şifresini üçüncü kişilerle herhangi bir şekilde paylaşmaması gerektiğinin bilincindedir. Bu hususta, Kullanıcılar, kullanıcı şifre ve adının kendi ihmal yahut kusurları nedeniyle başka kişiler tarafından kötü niyetle kullanılmasından dolayı doğrudan sorumlu olacaktır. LOJİSTER, bu sebeple ödemek zorunda kalacağı her türlü adli/idari para cezası ve/veya tazminat bedelini ilgili Kullanıcı’ya aynen rücu etme hakkına sahiptir.<br />
                    4.3.Müşteri, taşınmasını istediği Yükü taşıtmak için Platform üzerinde bir hizmet talebi oluşturduktan sonra Lojister, Platform’da kayıtlı Taşıyıcı’ lar tarafından kendisine iletilen taşıma ücret tekliflerini (“Teklif”) Müşteri bilgisi vermeksizin Platform’da listeleyerek Müşteri’nin kendisine en uygun gelen seçeneği seçmesine imkân sağlamaktadır. Özellikle belirtmek gerekir ki, Lojister yalnızca Müşteri ve Taşıyıcı’yı bir araya getiren Platform sağlama görevini üstlenmiş olup taşıma işlemlerini kendisi üstlenmemekte ve bu hususta sorumluluk kabul etmemektedir.<br />
                    4.4.Müşteri, Platform üzerinden Teklif’i kabul etmesi akabinde Yük’ünü, seçmiş olduğu Teklif’te belirtilen şartlara uygun olarak Taşıyıcı’ya teslim edecektir. Taşıyıcı da belirtilen şartlara uygun olarak Alıcı’ya yükü teslim edecektir.<br />
                    4.5.Lojister Platformu (Web Sitesi/IOS, Android tabanlı mobil uygulama) , www.lojister.com adresinde yer alan sitemizdeki web sayfaları ve ona bağlı tüm sayfalar ile akıllı telefonlardaki IOS/Android tabanlı mobil uygulamaları, Özkanlar Bilişim İç Ve Dış Ticaret Limited ŞTİ (“LOJİSTER”)’ın markasıdır ve onun tarafından işletilir.<br />
                    4. SÖZLEŞMENİN SÜRESİ<br />
                    <br />
                    5.1 İşbu Sözleşme, LOJİSTER ile Müşteri ve Taşıyıcı arasında Müşteri ve Taşıyıcının elektronik olarak onay verdiği tarih itibarıyla geçerlilik kazanır ve Müşteri, Taşıyıcı veya LOJİSTER tarafından feshedilene kadar yürürlükte kalır.<br />
                    5.2 Müşteri ve/veya Taşıyıcı, LOJİSTER’a Üye olmadıkları müddetçe Üyeler’in yararlandığı hizmetlerden, kampanyalardan yararlanamazlar veya bu yönde bir talepte bulunamazlar. 5. TARAFLAR’IN HAK VE YÜKÜMLÜLÜKLERİ<br />
                    <br />
                    6.1.Taşıyıcılar, platform üzerinde Müşterinin oluştumuş olduğu taşıma ilanına tekliflerini ileterek, müşterilerinin verilen teklifleri kabul etmesine onay vermiş sayılacaktır. Taşıyıcı, Platform’da yayımlanmak üzere ilettiği bilgileri, bilgilerde değişiklik yapıldığı takdirde düzenli aralıklarla güncellemekle sorumludur. Taşıyıcı ve Müşteri paylaştığı tüm bilgilerin doğru, güncel ve hukuka uygun olduğunu peşinen kabul, beyan ve taahhüt etmektedir.<br />
                    6.2.İşbu Sözleşme ile Taşıyıcı, Platform üzerinden kendisine bildirilecek Yük’leri Müşteri’nin talimatları doğrultusunda karayolu, havayolu, denizyolu ya da demiryolu üzerinden firmasına ait uygun araçlar ile basiretli bir taşımacılık şirketinden beklenen özen ve kalite ile taşıma hizmeti vermeyi taahhüt etmektedir. Taraflar, bu yükümlülüklerin tamamının Taşıyıcı tarafından yürütülecek lojistik faaliyetlerini tamamlayan tüm parçalar için geçerli olacağının bilincindedir.<br />
                    6.3.Taşıyıcı, Platform’a kayıt olmak için ticari unvan, marka, yetkili kişi bilgileri, iletişim bilgisi, vergi dairesi, vergi numarası, Platform üzerinden vermeyi taahhüt ettiği her türlü hizmet için yasal olarak gerekli izin, ruhsat, lisans (varsa), nitelik, deneyim ve kabiliyete sahip olduğunu gösterir belgeler, SRC belgesi, ehliyet, diploma, trailer type, servis yetki belgesi, Psikoteknik Belgesi, İş güvenliği belgesi, ticaret sicil belgesi, oda kayıt belgesi, referans bilgisi ve kayıt anında istenebilecek diğer her türlü bilgi ve belgeyi eksiksiz ve güncel olarak paylaşmayı peşinen kabul etmektedir. Bu bilgilerin doğruluğunu ve güncelliğini kontrol etmekle Lojister yükümlü değildir. Söz konusu bilgilerin yanlış veya eksik olması nedeniyle Taşıyıcı’nın yahut 3. kişilerin uğrayacağı her türlü zarardan sorumluluk Taşıyıcı ve Müşteri’ye aittir.<br />
                    6.4.Taşıyıcı, Müşteri’ye ait Yük’leri Lojister tarafından bildirilen yükleme yerinden alarak, Müşteri tarafından bildirilen yere objektif özen yükümlülüğü çerçevesinde taşıyarak teslim edecektir.<br />
                    6.5.Lojister, Sözleşme kapsamında gerçekleştirilecek taşıma hizmetleri ile ilgili olarak Taşıyıcı’ya (i) taşıma hizmetinin süresi, (ii) hangi şartlarla yapılacağı (iii) hizmet bedeli gibi konularda gerekli bilgilendirmeyi taşıma hizmeti öncesinde Taşıyıcı ve Müşteriye Platform (Web Sitesi veye mobil uygulama) üzerinden gerçekleştirecektir. Tarafların yanlış adres bildirimi ya da hiçbir bilgi sahibi olamadığı iddiaları Lojister tarafından kabul edilemez.<br />
                    6.6.Taşıyıcı, Platform üzerinden kendisine ait verdiği bilgilerin değişmesi halinde Platform üzerinden yapılan değişiklikleri güncellemekle sorumludur. Taşıyıcının verdiği bilgilerin değişmesi sebebiyle Lojister’ın veya Müşterinin Taşıyıcıya ulaşamaması nedeniyle taşıma hizmeti işinin gecikmesi veya hiç yapılamaması halinde 3. Kişilere karşı Lojister sorumlu değildir. Taşıyıcı, ilgili mevzuatlarda öngörülen standartlara uygun araçları tedarik edecektir. Bu hususta Taşıyıcı, tedarik edeceği araç/araçların hepsinin Müşteri’nin taşıtmak istediği Yük’ü taşımaya elverişli olduğunu peşinen kabul, beyan ve taahhüt etmektedir.<br />
                    6.7.Taşıyıcı’lar, “3D Secure ödeme sistemi” ile Lojister’a bildirmiş olduğu Teklif’te belirtilen hizmet bedeli tutarını irsaliye karşılığında Lojisterden tahsil edecektir.<br />
                    6.8.Taşıyıcı, Platform’da taahhüt ettiği hizmet süresine uygun olarak ve yine Platform üzerinden belirttiği koşullarda taşıma hizmetini gerçekleştirmekle yükümlüdür. Yük’ün varma yerinde oluşabilecek aksaklıklar nedeniyle teslimi zamanında gerçekleştirilemiyorsa veya herhangi bir şekilde Taşıyıcı’nın geç kalmasından kaynaklı ortaya çıkan ek masraftan Lojister sorumlu tutulamayacak olup doğabilecek ek masraflar ile Müşteri’nin uğrayabileceği doğrudan ve dolaylı zararlardan kusuru oranında Taşıyıcı Sorumlu olacaktır.<br />
                    6.9. Yük’ün varma yerinde oluşabilecek aksaklıklar nedeniyle yük zamanında boşaltılamıyorsa veya herhangi bir şekilde Alıcının teslim mahallinde bulunmamasından kaynaklı ortaya çıkan ek masraftan Lojister sorumlu tutulamayacak olup doğabilecek ek masraflar ile Taşıyıcı’nin uğrayabileceği doğrudan ve dolaylı zararlardan kusuru oranında Müşteri sorumlu olacaktır.<br />
                    6.10.Taşıyıcı, Sözleşme konusu hizmeti vermeye yetkili olduğunu, bu konuda yasal mevzuatın aradığı tüm belge ve sertifikalara, yetki belgesine ve yasal merciiler tarafından talep edilecek sair tüm belgelere sahip olduğunu, tedarik edeceği araçların ilgili mevzuatlar çerçevesinde taşıma hizmeti vermeye uygun ve Sözleşme’de belirtilen teknik ve yasal gerekliliklere uygun (aracın; C2 belgesi, R2 belgesi, SRC belgesi, psikoteknik rapor, plaka, ruhsat, zorunlu trafik sigortası, muayene belgesi gibi ilgili lojistik organizasyonunun yapılması için gereken ehliyetlere sahip olması gibi) olduğunu peşinen kabul, beyan ve taahhüt etmektedir.<br />
                    6.11.Taşıyıcı, Müşteri’nin yükünü taşıma amacı ile Müşteri tarafından talep edilen araç ve şoförü, ilgili ilanda belirtilmiş olan tarih ve saatte Yük’ün teslim alınacağı yerde hazır bulunacağını taahhüt etmektedir. Aksi halde Lojister, istediği başka firmadan araç temin etmek ve temin ettiği araç için ödediği fiyat, gider ve bu nedenle yaptığı tüm ek masrafları ve uğradığı doğrudan ve dolaylı zararları Taşıyıcı’ya rücu etme hakkına sahiptir. Yük’ün alındığı işyerinde kurallara tam uyulması gerekmekte olup oluşabilecek zararları işin ifasını gerçekleştirecek Taşıyıcı’nın sorumluluğundadır. Ayrıca Taşıyıcı’nın Müşteri tarafından talep edilen sayı ve özellikte aracı, talep edilen süre içerisinde hazır bulunduramaması nedeniyle, taşıma hizmetinin gerçekleştirilememesi veya Yük’ün varma yerine tesliminde gecikme olması halinde Taşıyıcı, Lojister ’ın Müşteri’ye olan sorumluluğundan dolayı uğradığı tüm doğrudan ve dolaylı zararları tazmin edecektir. Taşıyıcı ve Lojister, Taşıyıcının yükümlülüklerine aykırı davranışı nedeniyle Lojister ’ın herhangi bir zarara uğraması ve bu zararı tazmin etme yükümlülüğü altına girmesi durumunda, ilgili tutarın Taşıyıcı‘ya kusuru oranında rücu edilebileceği hususunda mutabık kalmışlardır.<br />
                    6.12.Taşıyıcı ve Müşteri, Yük’ün yüklenmesi, istiflenmesi, boşaltılması ve ambalajlanması sırasında bulunduğu tesislerdeki tüm kurallara aynen uymayı kabul, beyan ve taahhüt etmektedir. Taşıma hizmeti süresince, taşınan Yük’te veya 3. şahıs ve tesisler nezdinde oluşabilecek tüm zararlardan kusuru oranında Taşıyıcı, yükün boşaltılması alıcıdan kaynaklı gecikme yaşanmasından Müşteri sorumludur.<br />
                    6.13.Taşıyıcı, teslimi yapılacak Yük’leri Sözleşme hükümleri ve Platform’da kendisinin belirttiği miktarda ve taşıma süresi içerisinde bizzat taşımak ve teslim noktasına teslim ile mükelleftir. Taşıma süreleri Müşteri’nin Platform’da beyan ettiği şekilde kabul edilecektir.<br />
                    6.14.Yüklenici, taşıma işini bizzat kendi araç ve şoförleriyle yapsın yahut yapmasın taşıma işi gerçekleştirilirken meydana gelen eylem ve işlemlerinden birinci dereceden sorumlu olup işi alt yükleniciye yaptırmış olması Taşıyıcının bu sorumluluğunu sona erdirmemektedir. Bu sorumluluk taşıma hizmetinin verilmeye başlanmasından sona ermesine kadar (belirlenen taşıma şekline göre Taşıyıcı tarafından teslim edilen Yükün ilgili Alıcı’ya tesliminin tam ve eksiksiz olarak yapılmasına kadar) devam etmektedir.
                    5.15. Taşıyıcı, Sözleşme kapsamında taşıması gerçekleştirilen Yükler veya bu Yük’ler ilgili her türlü malzeme, teçhizat veya aletlerin sevk edilmeleri sırasında (i) kısmen veya tamamen hasara uğramaları, (ii) zayii olmaları, (iii) kalite ve niteliklerinde değişiklik olması ve bunlarla sınırlı olmamak üzere kendi kusuru sebebiyle 3. şahıslarda, Lojister ’ın çalışanlarında, işyerinde ve/veya çevrede bir zarar meydana gelmesi durumunda, bu durumlardan doğan tüm doğrudan ve dolaylı tazminat tutarlarını kusurları oranında ödeyeceğini, bu hususta Lojister’a herhangi bir rücu talebinde bulunamayacağını, peşinen kabul ve beyan etmektedir.<br />
                    6.16.Taşıyıcı, hizmet sağlarken kullanacağı araçlarda Yük’ün taşınması için gerekli malzemelerin bulunması konusunda Müşteri’ye karşı sorumludur. Lojister sistemin ve Müşteri’nin güvenliğini sağlamak amacıyla gerekli gördüğü durumlarda, Taşıyıcının yükümlülüklerini yerine getirip getirmediğini tespit etmek amacıyla bilgi isteyebilir ve inceleme yapabilir. Bir karışıklığa mahal vermemek adına belirtmek gerekir ki, bu bilgi talebi ve inceleme hiçbir zaman sorumluluğun kontrolünü bir taahhüt anlamına gelmeyecektir.<br />
                    6.17. Taşıyıcının gerçekleştirdiği taşıma işinin Lojister tarafından belirlenen standartlara ve/veya yasal mevzuata aykırı olması nedeniyle Lojister’a kamu kurum ve kuruluşları tarafından cezai işlem uygulanması halinde, söz konusu ceza da dahil olmak üzere, Lojister’ın uğradığı ve uğrayacağı tüm zararlardan kusuru oranında Taşıyıcı sorumludur. Lojister, herhangi bir şekilde bu zararları ödemek zorunda kalması durumunda bu miktarları Taşıyıcı’ya kusuru oranında rücu edebilecektir.<br />
                    6.18.Lojister, Taşıyıcı’ nın logosunu 3.şahıslarla paylaşma hakkını saklı tutar.<br />
                    6.19.İşbu Sözleşme kapsamında gerçekleştirilecek her türlü taşıma işlemi Taşıyıcının kendi yahut çalıştırdığı alt yüklenicinin araçları ve çalışanları ile sağlanacaktır. Lojister, Taşıyıcı’nın çalışanları tarafından 4857 sayılı İş Kanunu, 6331 sayılı İş Sağlığı ve Güvenliği Kanunu ve ilgili diğer mevzuat hükümlerine dayanılarak talep edilen tazminat ve sair hak talepleri karşısında herhangi bir sorumluluğu söz konusu olmayacak, bu hususta açılan davalarda taraf teşkil etmeyecektir.<br />
                    6.20.Hizmet Talebi’ne ilişkin tüm sorumluluk Müşteriye aittir. Lojister, Müşteri’den gelen bilgileri salt Platform vasıtasıyla ilgili Taşıyıcılar ile paylaşmakta olup bu hususta hiçbir sorumluluk kabul etmemektedir. Hizmet Talebi akabinde Müşteri, listelenen Taşıyıcının tekliflerini karşılaştırarak kendisine en uygun gelen, bu aşamada henüz anonim haldeki Müşterinin teklifini seçtikten sonra ödeme yaparak onaylayacaktır.<br />
                    6.21.Müşteri, teklifi onaylayıp, ödemeyi yapıncaya kadar teklif sunan Taşıyıcınn unvan ve logosunu göremeyecek, ancak teklifi kabul ederek ödeme yapması akabinde Lojister yetkilisi tarafından siparişi teyit edildikten sonra ilgili Taşıyıcının unvan ve benzeri bilgilerini görebilecektir.<br />
                    6.22.Taşıyıcı, Müşteri tarafından yapılan rezervasyonun ücreti, yükün yola çıkış saatinden 24 saat öncesine kadar ilanı yayından kaldırabilecektir.<br />
                    6.23.Müşteri, teklifi onaylayıp ödemeyi yaptıktan sonra iletilen son tarih ve saatte yapılacak iptal ya da değişiklik taleplerinden doğacak tüm zararları ödemeyi kabul etmektedir.<br />
                    6.24.Müşteri, Platform’da kabul ettiği Teklif’e ilişkin hizmet bedelini, Platform’da yer alan online ödeme sistemi ile banka kartı, kredi kartı veya benzer bir ödeme aracı ile diğer ödeme sistemleri vasıtasıyla anında online ödeme de yapabilecektir. Online ödeme sistemi ile ödeme seçeneği kullanılarak yapılan ödemelerde, kartın hamili haricinde bir başkası tarafından hukuka aykırı şekilde kullanılması halinde 23.02.2006 tarihli 5464 sayılı Banka Kartları ve Kredi Kartları Kanunu ve 10.03.2007 tarihli ve 26458 sayılı Resmi Gazete’de yayımlanan Banka Kartları ve Kredi Kartları Hakkında Yönetmelik hükümlerine göre işlem yapılacaktır<br />
                    6.25.Müşteri, Platform’a beyan ettiği isim, adres, telefon, e-posta, vergi dairesi gibi her türlü bilginin güncel, doğru ve eksiksiz olduğunu kabul, beyan ve taahhüt etmektedir. Lojister, söz konusu bilgilerin doğruluğunu ve güncelliğini kontrol etmekle yükümlü değildir. Söz konusu bilgilerin yanlış veya eksik olması nedeniyle Müşterinin yahut 3. kişilerin uğrayacağı zararlardan sorumluluk Müşteri’ye aittir.<br />
                    6.26.Müşteri, Platform üzerinden oluşturduğu üyeliğe ilişkin kullanım haklarını, kullanıcı adı ve hesabına ait şifreyi başkasına devredemeyecektir.<br />
                    <br />
                    7. FATURALANDIRMA VE ÖDEME<br />
                    7.1 Müşteri, her bir Elektronik Teklif’e ait navlun tutarını sistemde görecek ve nakliyesinin yapılmasını istediği teklifler arasından kendisine en uygun olan teklifi seçtikten sonra ilgili navlun bedelini LOJİSTER ’a ödeyecektir. Ödemeler, LOJİSTER ’ın Web Sitesi veya mobil uygulama üzerindeki güvenlik sertifikalı ara yüzden kredi kartı, banka kartı ya da LOJİSTER ’ın kurumsal banka hesabına havale/EFT yoluyla yapılacaktır. LOJİSTER hizmet alımı öncesi veya sonrasında firmaya yönlendirilen alt tedarikçilere ve/veya alt tedarikçi personeline ödeme ve mail-order olarak belirtilen kredi kartı bilgilerinin paylaşımı üzerinden ödeme yöntemlerini kullanmamaktadır, bu yöntemler üzerinde yapılacak para transferleri sonucunda oluşan maddi kayıplarda Müşteri, Taşıyıcı veya Alıcı sorumlu olup LOJİSTER sorumlu tutulamaz.<br />
                    7.2 Sözleşme konusu hizmete ilişkin ödemenin kredi kartı ile yapılması durumunda, kredi kartı sahibinin ya da hizmetin verileceği tarafların farklı olmasından kaynaklanabilecek, kredi kartının yetkisiz kişilerce haksız ve hukuka aykırı olarak kullanılması da dahil olmak üzere her türlü hukuki risk, Müşteri’ ye aittir. Müşteri, bahsi geçen durumlarda herhangi bir şekilde zarara uğraması halinde LOJİSTER’dan hiçbir talepte bulunmayacağını kabul ve taahhüt eder.<br />
                    7.3 Müşteri tarafından, Sözleşme konusu Hizmete ilişkin ödemenin herhangi bir Banka’ya ait ATM cihazından ya da şubesinden “hesaba yatırma” şeklinde yapılması durumunda, hizmet bedelinin işbu Sözleşmede belirtilen şartlar çerçevesinde Müşteri’ ye iade edilmesinin gerektiği hallerde kullanılmak üzere kendisine ait bir banka hesabına ait IBAN numarasını doğru ve eksiksiz bir şekilde LOJİSTER platformuna bildirmeyi ve LOJİSTER tarafından bu IBAN numarasına iade yapılmasına muvafakat ettiğini kabul ve taahhüt eder. Müşteri işbu maddede bahsi geçen şekilde IBAN numarasını LOJİSTER’a bildirmediği taktirde herhangi bir talepte bulunamaz.<br />
                    7.4 Herhangi bir navlun bedelinin ödenmesine rağmen LOJİSTER’dan kaynaklanan nedenlerle Hizmet’in gerçekleştirilememesi durumunda, Müşteri, LOJİSTER ’a ödenen tutarın iadesini talep etmek veya bu tutarı daha sonra talep edilecek Hizmet bedellerinden düşülmek üzere LOJİSTER nezdinde tutmak hakkına sahiptir.<br />
                    <br />
                    8. İPTAL VE İADE KOŞULLARI<br />
                    8.1.Herhangi bir sebeple "Üye"likten çıkarılmış veya "Üye"liği durdurulmuş veya üyeliği askıya alınmış kullanıcının PLATFORMA girmek için yeni üyelik hesabı açması ve bu yeni üyeliğinin LOJİSTER tarafından tespit edilmesi halinde; bu kullanıcının tüm "LOJİSTER Üyelik Hesapları"nı, herhangi bir ihtara gerek olmaksızın iptal etme ve işbu sözleşmeyi herhangi bir ücret iade, tazminat veya cezai şart yükümlülüğü olmadan tek taraflı olarak feshetme hakkını LOJİSTER saklı tutmaktadır.<br />
                    8.2."Yük sahibi/Müşteri ve Taşıyıcı", platform üzerinden "LOJİSTER" web site ve mobil uygulamaya ait alt yapıyı kullanarak yapmış olduğu hizmet alma ve hizmet sağlama talepleri ile "LOJİSTER" tarafından belirlenmiş üyelik şartlarını ve usullerini de kabul etmiş sayılır. İstisnai durumlar hariç, "Yük sahibi/Müşteri ve Taşıyıcı" tarafından yapılan hizmet alma ve hizmet sağlama talepleri geri çekilemez veya iptal edilemez.<br />
                    8.3.Sadece ürünün “Yük veren/Müşteri” tarafından Taşıyıcıya verilmemesi veya Taşıyıcıya verilmeden sağlanması talep edilen hizmetin Yük sahibi/ Müşteri tarafından iptal edilmesi halinde; LOJİSTER hesabında bloke edilen ödeme 750 TL İptal Bedeli  cezai şart düşülerek Yük Sahibine iade edilir.<br />
                    8.4.İADE:Taşıyıcının emtiayı teslim aldığını, teslim alma saatinden itibaren 24 saat içinde sistem üzerinden onaylaması üzerine hizmet bedeli Taşıyıcıya ödenir. Ancak Alıcı tarafından teslim edilen emtiada uygunsuzluk veya herhangi bir sorun yaşaması halinde; ürünü teslim alma anından başlayacak 24 saatlik süre içinde “Alıcı” ya da “Müşteri”, “LOJİSTER” Müşteri Hizmetlerini arayarak sunulan hizmete ilişkin yaşadığı sorunu bildirmelidir. Müşteri Hizmetlerine sorununu bildirmesinden itibaren 7 iş günü süre içinde “Yük sahibi/Müşteri” “Taşıyıcıya”ya karşı yasal yollara müracaat ettiğini belgeleyen evrak sunması halinde; ürün bedeli Taşıyıcı’ya iade edilmeyecek, uyuşmazlık sonuçlanana dek LOJİSTER’ ın anlaşmalı ödeme kuruluşunun hesabında bloke edilecek, başvurulan merciinin kararı çıktığında bu karara göre hareket edilecektir. “Yük sahibi/Müşteri”, uyuşmazlık konusu karara bağlanana dek ürün bedelinin bloke edilmesi nedeniyle “LOJİSTER”a karşı şikâyet/dava yoluna başvurmayacağını, “LOJİSTER”dan herhangi bir talepte bulunmayacağını kabul, beyan ve taahhüt eder.<br />
                    <br />
                    9. SİGORTA YÜKÜMLÜLÜĞÜ<br />
                    9.1.Taşıyıcı, sigortaların Sözleşme yürürlükte olduğu sürece kesintisiz olarak devam etmesini sağlayacaktır. Taşıyıcı, sigorta primlerinin yatırıldığını ve sigorta poliçelerinin yenilendiğini, belgesi ile birlikte Lojister’a en geç poliçenin yenilenme tarihine kadar belgelendirerek bildirecektir. Taşıyıcı, taşıma esnasında yalnızca bu poliçelerin taşıma için kullanılan araçlar için kullanılacağını kabul, beyan ve taahhüt eder. Taşıyıcı, bu madde çerçevesinde yükümlülüklerini ihlal etmesi halinde Lojister’ ın Sözleşme’yi derhal fesih hakkı olduğu gibi, doğabilecek her türlü zararı da Taşıyıcı tazmin edecektir. Taşıma sırasında zarar meydana gelmesi halinde ortaya çıkan zararın sigorta poliçe limitleri dışında kalması halinde, zarar ve ziyanın tazmininde tamamen Taşıyıcı sorumlu olacaktır.<br />
                    9.2.Teslim noktasına ulaşan ürünler hasarlı ise, hasarlı ürünün veya ürünlerin araç yükleme/boşaltma noktasından ayrılmadan fotoğrafları Müşteri veya Alıcı tarafından çekilip, teslim evrakına hasar gören ürün cinsi ve net ürün sayısı yazılıp şoförün de imzalayacağı tutanak tutulmalı ve durum vakit kaybedilmeden LOJİSTER ile paylaşılıp sigorta süreci başlatılmalıdır.<br />
                    <br />
                    10. ORTAK HÜKÜMLER<br />
                    10.1.Platform’a sadece temyiz kudretini haiz, 18 yaşından büyük kişiler Kullanıcı olarak kayıt olabilmektedir. Kullanıcılar, Platform’a ancak, kayıt formunda kendilerinden talep edilen bilgileri doğru, eksiksiz ve güncel olarak doldurmaları halinde kayıt olabileceklerdir.<br />
                    10.2.Lojister, Taşıyıcıların sıralanması ve gösterilmesinde objektif kriterler dışında hiçbir kriteri esas almayacaktır.<br />
                    10.3.Lojister, her taşıma sonrası Müşteri’yi arayarak ya da online anket göndererek kendisine aşağıdaki soruları yönelterek aldığı hizmet hakkında Taşıyıcıyı puanlamasını isteyebilecektir:<br />
                    Yük’ünüz zamanında ve hasarsız alındı mı? ( Müşteri 1 ile 5 arasında bir puan verecektir.)<br />
                    Zamanında sorunsuz bir şekilde teslim edildi mi? ( Müşteri 1 ile 5 arasında bir puan verecektir.)<br />
                    Taşıyıcı' nın operasyonel yönetimi ve iletişimi nasıldı? (Müşteri 1 ile 5 arasında bir puan verecektir.)<br />
                    Bu puanların ortalamaları alınarak Taşıyıcı’nın Platform’daki havuzuna eklenecek olup, her hafta önceki hafta alınan puanlar güncellenerek Taşıyıcı’ya yıldız edinme şansı sağlayacaktır.<br />
                    10.4.Taşıyı ile Müşteri arasında akdedilecek işbu Sözleşme dışındaki taşıma sözleşmesine Lojister hiçbir suretle taraf olmayacaktır. Bahse konu taşıma sözleşmesi ile Sözleşme arasında bir uyuşmazlık olması durumunda işbu Sözleşme hükümleri esas alınacak olup Lojister herhangi bir şekilde uyuşmazlıklara taraf edilemeyecektir.<br />
                    10.5. Platform’daki bilgilerin, güncelliği, doğruluğu, şartları, kalitesi, performansı, pazarlanabilirliği, belli bir amaca uygunluğu ve Platform’da yer alan ve bunlarla sınırlı olmayan, bunlarla bağlantılı veya bağımsız diğer bilgi, hizmet veya ürünlere etkisi ile tamlığı hakkında herhangi bir şekilde açık yahut örtülü olarak garanti verilmemekte ve taahhütte bulunulmamaktadır. Platformdaki bilgilerin güncel olmaması doğrudan Müşteri ve Taşıyıcıyı sorumlu kılar. Lojister yazılımının teknik aksaklığından kaynaklanması halinde bu hüküm uygulanmaz. Ayrıca, Lojister, Platform dahilinde erişime açtığı hizmetler ve içeriklerden hangisinin ücrete tabi olacağını belirlemekte tamamen serbesttir.<br />
                    10.6.Taşıyıcı, Müşteri ve Lojister arasında kurulmuş ve/veya kurulacak Sözleşmeye konu edilen ticari ilişki gereğince Taraflar’ın her birinin birbirlerine ait işle ilişkili kişisel veri niteliği taşıyan yazılı ve/veya sözlü bilgilere ulaşacak olması sebebiyle,<br />
                    (a) Kendilerine iletilen kişisel verileri 6698 sayılı Kişisel Verilerin Korunması Kanunu ve ilgili mevzuat (“Kişisel Verilerin Korunması Mevzuatı”) başta olmak üzere Türk Hukukuna uygun şekilde gizli tutacaklarını, kişisel verilerin hukuka aykırı şekilde işlenmesini ve söz konusu kişisel verilere hukuka aykırı bir şekilde erişilmesini önleyeceklerini, akdi İlişki konusuyla sınırlı bir şekilde ve sınırlı bir süre ile kullanıp ve saklayacaklarını; veri sahibinin yazılı onayı olmaksızın kişisel verileri işlemeyeceklerini, söz konusu kişisel verileri yalnızca Sözleşme konusu edimlerin yerine getirilebilmesi bakımından zorunlu olduğu ölçüde kullanacaklarını, işin gerektirdiği süre boyunca saklayacaklarını ve işlenmesini gerektiren sebeplerin ortadan kalkmasını takiben yasal zorunluluk arz eden durumlar hariç olmak üzere veri sahibinin bu hususta yapacağı bir ihbar ya da ihtara hacet kalmaksızın derhal sileceklerini, yok edeceklerini veya anonim hale getirmeye ilişkin kayıtları tutacaklarını ve Kişisel Verilerin Korunması Mevzuatı gereği bu kayıtları üç yıl boyunca saklayacaklarını kabul ve beyan eder.<br />
                    (b) Kişisel verilere erişen ve verileri elinde bulunduran sıfatıyla Taraflar, bu verilerin hukuka aykırı olarak işlenmesini önlemek, kişisel verilerin güvenli bir biçimde saklanmasını sağlayan mevzuata uygun yedekleme programlarını kullanmak, kanuni süreler ve amacı ile sınırlı olmak kaydıyla muhafazasını sağlamak amacıyla Kişisel Verilerin Korunması Mevzuatı uyarınca gerekli her türlü teknik ve idari tedbirleri almayı ve bu konuda veri sahibinden gelen talimatlara uyacaklarını kabul, beyan ve taahhüt eder.<br />
                    (c) İşbu Gizlilik ve KVK Taahhüdü ve Kişisel Verilerin Korunması Mevzuatı’nda yer alan düzenlemelere aykırı davranan Taraf, ihlal sebebiyle zarara uğrayan diğer Taraf aleyhine tahakkuk eden idari para cezaları da dahil olmak ve fakat bununla sınırlı olmamak üzere ihlalden kaynaklanan zararları, ihlal sebebiyle zarara uğrayan Taraf’ın ilk yazılı talebi üzerine nakden ve defaten tazmin etmeyi kabul, beyan ve taahhüt eder.<br />
                    (d) Tarafların personelinin, alt çalışanlarının ve bağlı olarak çalışan diğer kişilerin kişisel verilere erişim ve işleme yetkilerini Kişisel Verilerin Korunması Mevzuatı’na uygun olarak sadece Sözleşme’ye konu edilen edimlerin yerine getirilmesi için gerektiği kadar tanımlayacaklarını; bu erişim yetkilerini kullanırken personelin, alt çalışanların ve bağlı olarak çalışan diğer kişilerin erişilen bilgiler ve erişim için kullandığı şifreleri/metotları hiç kimse ile paylaşmamalarını sağlayacaklarını; personelin, alt çalışanların ve bağlı olarak çalışan diğer kişilerin Kişisel Verilerin Korunması Mevzuatı’nda belirtilen yükümlülükleri kapsamında bilgilendirme yapacaklarını; bu Gizlilik ve KVK Taahhüdü’nün imzasından sonra işten ayrılmış olsalar dahi personelin, alt çalışanların ve bağlı olarak çalışan diğer kişilerin işbu Gizlilik ve KVK Taahhüdü’nde belirtilen yükümlülüklere aykırı davranmayacaklarını ve böyle davranmaları halinde ihlal sebebiyle zarara uğrayan Taraf’ın aleyhine tahakkuk eden idari para cezaları dahil olmak ve fakat bununla sınırlı olmamak üzere ihlalden dolayı doğrudan uğrayacağı zararlardan kusurları oranında sorumlu olacaklarını kabul ve beyan eder.<br />
                    (e) Sözleşme’nin yürürlük süresi boyunca Taraflar’ın Kişisel Verilerin Korunması Mevzuatı’dan doğan yükümlülükleri devam edecektir; ancak her halükarda, Sözleşme her ne sebeple olursa olsun sona erdikten sonra birbirlerine iletilen kişisel verileri veri sahibine iade edeceklerini, kayıtlarında arşiv amaçlı dahi olsa hiçbir kopya tutmayacaklarını ve tüm kişisel verileri yok edeceklerini; Taraflar’ca birbirlerine iletilen her türlü bilgi ve belgeye ilişkin talebi, talebin iletildiği tarihten itibaren [3 (üç)] gün içinde karşılamayı taahhüt ederler. (f) Herhangi bir veri ihlali olması durumunda, durumu derhal veri sahibi Taraf’a bildireceklerini, Lojisterın, Taşıyıcının ve Müşterinin şirketinde kişisel veri içeren sistemleri üzerinde gerekli denetimleri yapma veya yaptırmaya hakkı olduğunu kabul ve beyan eder.<br />
                    <br />
                    11. SÖZLEŞMENİN FESHİ<br />
                    11.1 Lojister, işbu Sözleşme süresince herhangi bir zamanda bildirimde bulunmaksızın işbu Sözleşmeyi herhangi bir tazminat ödemeksizin derhal etkili olacak şekilde feshedebilecektir. Taşıyıcı ve Müşteri işbu sözleşme süresince platform aracılığıyla aktif teklif ve ilanı olmadığı sürece Lojister’ a yazılı bildirimde bulunarak ve fesih sebebiyle oluşacak zararı gidermek suretiyle işbu sözleşmeyi feshedebilecektir.<br />
                    11.2 Taşıyıcı ve/veya Müşterinin Sözleşme’de belirtilen yükümlülüklerinden herhangi birini tam ve gereği gibi yerine getirmemesi ve karşı Tarafça iletilen yazılı ihtara rağmen söz konusu aykırılığı tebliği müteakip 1 (bir) hafta içerisinde ortadan kaldırmaması halinde, işbu Sözleşme ihtarı yapan Tarafça herhangi bir tazminat ödemeksizin haklı nedenle derhal etkili olacak şekilde feshedilebilecektir.<br />
                    11.3 Taşıyıcı veya Müşteriden birinin kendi isteğiyle olsun ya da olmasın iflası, iflas ertelemesi, konkordato ilan etmesi ya da herhangi bir borcu nedeniyle benzer bir duruma düşmesi veya hukuki statüsünü kaybetmesi halinde; diğer Taraf Sözleşmeyi yazılı bir bildirimde bulunarak derhal feshedebilecektir.<br />
                    11.4 İşbu maddede belirtilen fesih hallerinin gerçekleşmesi halinde Müşteri fesih tarihinden itibaren varsa bakiye borcunu üç gün içerisinde LOJİSTER’a ödeyecektir. Aksi halde LOJİSTER Madde 6 hükmüne göre faiz faturası düzenleme hakkına sahip olur.<br />
                    <br />
                    12. KANUNİ DELİL ANLAŞMASI<br />
                    Tarafların düzenlediği makbuz ve faturalar da dâhil tüm yazışmaları ve ihbarları, raporları faks mesajları ve kayıt dokümanları ile e-mail mesajları HMK uyarınca Taraflar arasında kesin ve münhasır kanuni delil sayılacak ve böyle kabul edilecektir.<br />
                    <br />
                    13. REHİN HAKKI LOJİSTER<br />
                    Müşteri’nin ve Taşıyıcı’ nın vadesi gelmesine rağmen ödenmeyen ücretleri ile ilgili olarak, söz konusu ücretlerin ödenmesine kadar mallar, vasıtalar veya bunlarla bağlantılı evraklar üzerinde rehin hakkını kullanabilecektir.<br />
                    <br />
                    14. GİZLİLİK VE SIR SAKLAMA YÜKÜMLÜLÜĞÜ<br />
                    14.1. Lojister’ın Taşıyıcı yahut Müşteri ile paylaştığı her türlü ticari, teknik, mali ve ilgili diğer konulara ilişkin bilgi ve belgeler “gizli bilgi” olarak kabul edilecek ve sır saklama yükümlülüğüne tabi olacaktır.<br />
                    14.2.Taraflar, bu Sözleşme kapsamında birbirleriyle paylaştıkları gizli bilgileri korumak için basiretli bir tacir olarak gerekli özeni gösterecek ve bu bilgilerin korunmasını sağlayacaktır.<br />
                    14.3.Taraflar gizli bilgileri ve hizmet yükümlülüğünün ifası sırasında vakıf oldukları diğer bilgileri üçüncü şahıslara ve kuruluşlara açıklamayacaklar, yetkisiz kişilere bu bilginin ulaşmasını engelleyecekler, izinsiz kullanıma karşı önlem alacaklar ve aksi bir durum ortaya çıkması halinde durumu derhal birbirlerine acele hallerde sözlü olarak daha sonrada yazılı olarak bildireceklerdir.<br />
                    14.4.Lojister, ticari amaçla Taşıyıcı’nın ve Müşteri’nin kişisel bilgilerini kullanabilir ve 3. kişiler ile Platform’da detaylıca paylaşılan “Lojister Gizlilik Politikası ve Aydınlatma Metni”ne uygun şekilde kullanıp paylaşabilecektir. Bu hususta özellikle, Taşıyıcı’nın ve Müşteri’nin haklarını ve güvenliklerini korumak için yetkili idari veya adli otoriteler tarafından usulüne göre yürütülen bir araştırma veya soruşturmanın yürütülmesi amacıyla bilgi talep edilmesi ve yetkili hukuki otoriteler tarafından çıkarılan ve yürürlükte olan kanun, kanun hükmünde kararname yönetmelik ve her türlü sair mevzuat gereği hukuk kurallarının getirdiği zorunluluklara uyulması gereken durumlarda ve yasal mevzuata uygun zorunluluklar kapsamında Taşıyıcı’nın ve Müşteri’nin kişisel bilgilerini 3. kişilerle paylaşabilecektir. Yine aynı amaç doğrultusunda Lojister, Müşteri’nin güvenlik kontrollerinin sağlanması için Taşıyıcı’ nın ticaret sicil, vergi levhaları, ticari sertifika bilgileri bu hususta hizmet veren 3. Kişilerle paylaşabilecektir.<br />
                    14.5.Taraflar, diğer tarafa ait gizli bilgilerin Sözleşme’ye aykırı biçimde açıklandığından haberdar olduğunda, derhal ve yazılı olarak karşı tarafa durumu bildirmekle yükümlüdür.<br />
                    14.6.Taraflar’ın gizlilik yükümlülüğü, hizmet ilişkisinin sona ermesinden sonra da süresiz olarak devam edecektir.<br />
                    14.7.Taşıyıcının kesinleşmiş mahkeme kararı ile tespit edilmiş olmak kaydıyla ağır ihmal veya kusuru nedeniyle Müşteri’nin veya 3. Kişilerin herhangi bir şekilde zarara uğraması ve/veya bu konudaki dava ve takiplerin Lojister’a yönelmesi halinde, Lojister, tüm zararlar ve ayrıca yargı giderleri, para cezaları ve avukatlık ücretlerini Taşıyıcıya rücu edebilecektir.<br />
                    <br />
                    15. MÜCBİR SEBEPLER<br />
                    15.1 Taraflar bu Sözleşme’den doğan yükümlülüklerini bir mücbir sebep olayı nedeni ile yerine getiremedikleri veya ifa etmekte geciktikleri takdirde bu temerrütten dolayı sorumlu tutulmayacaklardır. Yangın, deprem, sel gibi doğal afetler ile grev, lokavt ve sair beşeri afetler gibi işbu Sözleşme’nin imza tarihinde öngörülemeyen ve Taraflar’ın kontrolü dışında gerçekleşen olaylar mücbir sebep sayılır.<br />
                    15.2 Böyle bir olayın vukuu halinde, bu olaydan etkilenen taraf durumu ve olayın tahmini süresini ve doğurduğu etkilerin kapsamını diğer tarafa derhal yazılı olarak bildirecektir. Bu ihbarda mücbir sebebin niteliği açıklanacak ve mümkünse, mücbir sebebin o tarafın bu anlaşmadan doğan yükümlülüklerini ifa kabiliyeti üzerindeki etkileri analiz edilecektir.<br />
                    15.3 Tarafların işbu Sözleşme kapsamında taahhüt ettikleri edimleri mücbir sebep nedeniyle 30 günden fazla ifa edememesi halinde, işbu Sözleşme taraflardan birinin yazılı bildirimi doğrultusunda feshedilebilecektir. Tarafların hiçbiri bu anlaşmanın bir mücbir sebep olayından dolayı feshedilmesi sebebiyle diğer tarafa karşı sorumlu tutulamaz.<br />
                    <br />
                    16. FİKRİ MÜLKİYET HAKLARI<br />
                    16.1 WebSitesi, IOS, Android tabanlı mobil uygulama ve bu sistemler üzerinden sunulan hizmetler üzerindeki her türlü hak, mülkiyet ve menfaat LOJİSTER ’ya aittir. Web Sitesi’nin ve Mobil uygulamanın tasarımında, içeriğinde ve veri tabanı oluşturulmasında kullanılan bilgi ve/veya yazılımın kopyalanması ve/veya Web Sitesi’nden ve mobil uygulamadan faydalanmanın ötesinde kullanılması, Web Sitesi ve mobil uygulama dâhilinde bulunan her türlü resim, metin, imge, dosya vb. verilerin kopyalanması, dağıtılması, işlenmesi ve sair şekillerde kullanılması kesinlikle yasaktır. İşbu Koşullar kapsamında Müşteri- Taşıyıcı veya Müşteri- Taşıyıcı Yetkilisine yalnızca Web Site ve mbil uygulama üzerinden sağlanan hizmetlerden yararlanması için bedelsiz, devredilemez ve münhasır olmayan bir kullanım hakkı tanınmaktadır. İşbu Koşullar’da yer alan hiçbir hüküm Müşteri- Taşıyıcı veya MüşteriTaşıyıcı Yetkilisine kısmen ya da tamamen herhangi bir hak, mülkiyet ve menfaat tanındığı şeklinde yorumlanamaz. Müşteri- Taşıyıcı veya Müşteri- Taşıyıcı Yetkilisi, hiçbir şekilde Web Sitesi’nde ve mobil uygulamada çalıştırılan yazılımları kopyalayamaz, değiştiremez, çoğaltamaz, türev çalışmalar oluşturamaz, ters mühendisliğe tabi tutamaz, geri derleme ve sair şekillerde yazılımın kaynak koduna ulaşmaya çalışamaz.<br />
                    16.2 Müşteri- Taşıyıcı veya Müşteri- Taşıyıcı Yetkilisi, LOJİSTER’ a ait bilgilerin her türlü ortam ve dağıtım kanalı aracılığıyla (hali hazırda bilinen yahut sonradan geliştirilecek olan) kullanılması, kopyalanması, çoğaltılması, işlenmesi, uyarlanması, değiştirilmesi, yayınlanması, iletilmesi gösterilmesi ve dağıtılması, saklanması ve yedeğinin alınması için dünya çapında, münhasır olmayan, bedelsiz bir kullanım hakkı (alt lisans verme hakkı ile birlikte) vermektedir.<br />
                    16.3 Müşteri- Taşıyıcı veya Müşteri- Taşıyıcı Yetkilisi, LOJİSTER’ ın ve iştiraklerinin ticari unvanını, ticari markalarını, hizmet markalarını, logolarını, alan adlarını hiçbir şekilde kullanamaz.<br />
                    <br />
                    17. YÜRÜRLÜK<br />
                    İşbu Sözleşme, Gizlilik Politikası ve sözleşme ekindeki tüm belgeler Müşteri ve Taşıyıcının Web Sitesi’ne ve mobil uygulamaya erişmesi ve üye olması ile bu tarihte Lojister ile karşılıklı olarak kabul edilerek yürürlüğe girmiştir.<br />
                    <br />
                    18. TEBLİGATLAR<br />
                    Tarafların tebligat adresleri işbu sözleşmede belirtilen adresler olup, herhangi bir adres değişikliği platform üzerinden güncellenmediği sürece, söz konusu adreslere iletilecek tebligatlar geçerli addedilecektir. Taşıyıcıya ve Müşteriye sözleşme nedeniyle yapılacak tebligatlar sözleşme kapsamında belirtilen adrese yapılacak olup, bu adresler yasal tebligat mahalli sayılacaktır.<br />
                    <br />
                    19. DELİL SÖZLEŞMESİ VE İHTİLAFLARIN ÇÖZÜMÜ<br />
                    19.1.Sözleşme’den doğabilecek her türlü ihtilafta Platform üzerinden gönderilen e-mail, telefon görüşme kayıtları ve cep telefonuna gönderilen SMS bilgilendirme ve kayıtları delil niteliğinde olup, ayrıca Tarafların ticari defter ve kayıtları kesin delil olarak kabul edilecektir.<br />
                    19.2. İşbu Sözleşme Türk hukukuna tabi olup, Sözleşme’nin uygulanmasından ve yorumundan doğan ihtilaflarda Denizli Mahkemeleri ve İcra Daireleri yetkilidir<br />

                </p>
            </div>
            <h3 style={{ margin: "1rem 0 .25rem 0" }}>Cayma Hakkı Bildirimi</h3>
            <div style={{ display: "flex", width: "100%", height: "80px", overflowY: "scroll" }}>
                <p>
                    İPTAL VE İADE KOŞULLARI<br />
                    7.1.Herhangi bir sebeple "Üye"likten çıkarılmış veya "Üye"liği durdurulmuş veya üyeliği askıya alınmış kullanıcının PLATFORMA girmek için yeni üyelik hesabı açması ve bu yeni üyeliğinin LOJİSTER tarafından tespit edilmesi halinde; bu kullanıcının tüm "LOJİSTR Üyelik Hesapları"nı, herhangi bir ihtara gerek olmaksızın iptal etme ve işbu sözleşmeyi herhangi bir ücret iade, tazminat veya cezai şart yükümlülüğü olmadan tek taraflı olarak feshetme hakkını LOJİSTER saklı tutmaktadır.<br />
                    7.2."Yük sahibi/Müşteri ve Taşıyıcı", platform üzerinden "LOJİSTER" web site ve mobil uygulamaya ait alt yapıyı kullanarak yapmış olduğu hizmet alma ve hizmet sağlama talepleri ile "LOJİSTER" tarafından belirlenmiş üyelik şartlarını ve usullerini de kabul etmiş sayılır. İstisnai durumlar hariç, "Yük sahibi/Müşteri ve Taşıyıcı" tarafından yapılan hizmet alma ve hizmet sağlama talepleri geri çekilemez veya iptal edilemez.<br />
                    7.3.Sadece ürünün “Yük veren/Müşteri” tarafından Taşıyıcıya verilmemesi veya Taşıyıcıya verilmeden sağlanması talep edilen hizmetin Yük sahibi/ Müşteri tarafından iptal edilmesi halinde; LOJİSTER hesabında bloke edilen ödeme 750 TL İptal Bedeli  cezai şart düşülerek Yük Sahibine iade edilir.<br />
                    7.4.İADE:Taşıyıcının emtiayı teslim aldığını, teslim alma saatinden itibaren 24 saat içinde sistem üzerinden onaylaması üzerine hizmet bedeli Taşıyıcıya ödenir. Ancak Alıcı tarafından teslim edilen emtiada uygunsuzluk veya herhangi bir sorun yaşaması halinde; ürünü teslim alma anından başlayacak 24 saatlik süre içinde “Alıcı” ya da “Müşteri”, “LOJİSTER” Müşteri Hizmetlerini arayarak sunulan hizmete ilişkin yaşadığı sorunu bildirmelidir. Müşteri Hizmetlerine sorununu bildirmesinden itibaren 7 iş günü süre içinde “Yük sahibi/Müşteri” “Taşıyıcıya”ya karşı yasal yollara müracaat ettiğini belgeleyen evrak sunması halinde; ürün bedeli Taşıyıcı’ya iade edilmeyecek, uyuşmazlık sonuçlanana dek LOJİSTER’ ın anlaşmalı ödeme kuruluşunun hesabında bloke edilecek, başvurulan merciinin kararı çıktığında bu karara göre hareket edilecektir. “Yük sahibi/Müşteri”, uyuşmazlık konusu karara bağlanana dek ürün bedelinin bloke edilmesi nedeniyle “LOJİSTER”a karşı şikâyet/dava yoluna başvurmayacağını, “LOJİSTER”dan herhangi bir talepte bulunmayacağını kabul, beyan ve taahhüt eder.<br />

                </p>
            </div>
        </>
    )
}

export default Sozlesmeler;