package com.lojister.model.enums;

public enum AdvertisementProcessStatus {

    WAITING,
    BID_GIVEN,
    BID_APPROVED,
    PAYMENT_SUCCESSFUL,
    ASSIGNED_VEHICLE,
    STARTING_TRANSPORT,
    UPLOADED_DOCUMENT,
    CONTAINER_RECEIVED,
    CARGO_DELIVERED,
    CARGO_ON_THE_WAY,
    WAITING_WAYBILL,
    WAYBILL_DENIED,
    CARGO_COULD_NOT_BE_DELIVERED,
    CLIENT_CARGO_PROBLEM,
    COMPLETED,
    FINISHED,
    ENDING_TRANSPORT,
    TIMEOUT,
    HIDDEN

}
