package com.lojister.model.enums;

public enum TransportProcessStatus {

    WAITING,
    PAYMENT_SUCCESSFUL,
    CANCEL,
    APPROVED,
    ASSIGN_VEHICLE,
    STARTING_TRANSPORT,
    UPLOADED_DOCUMENT,
    CONTAINER_RECEIVED,
    CARGO_DELIVERED,
    CARGO_ON_THE_WAY,
    WAITING_WAYBILL,
    CARGO_WAS_DELIVERED,
    CARGO_COULD_NOT_BE_DELIVERED,
    WAYBILL_DENIED,
    CLIENT_CARGO_PROBLEM,
    ENDING_TRANSPORT,
    COMPLETED
}
